Revisar la correcta implementación de los controladores de tipo catalogo
DABEV/pret-back pull request #21
Opened 2022-07-18 00:14 UTC by GustavoLopez04

2022-07-18 19:44 UTC, GandyA23 requested changes
Revisar los comentarios y realizar sus respectivas correcciones.

2022-07-18 19:44 UTC, GandyA23 commented on src/main/java/mx/edu/utez/pret/controller/EstadoRepublicaController.java
> +@RequestMapping("/estadoRepublica")
Para los nombres de rutas, es mejor usar kebab-case que camelCase (estado-republica), cambiar a kebab-case.

2022-07-18 19:44 UTC, GandyA23 commented on src/main/java/mx/edu/utez/pret/controller/EstadoRepublicaController.java
> +        return new ResponseEntity<>(response.buildStandardResponse("Obtener todos los estadosRepublica",
En los mensajes que se retornan en las respuestas, no es necesario usar el nombre de la entidad en camelCase, es mejor mandar un mensaje escrito de manera normal (estado de la república)

2022-07-18 19:44 UTC, GandyA23 commented on src/main/java/mx/edu/utez/pret/controller/EstadoVacanteController.java
> +@RequestMapping("/estadoVacante")
Cambiar de camelCase pot kebab-case (estado-vacante).

2022-07-18 19:44 UTC, GandyA23 commented on src/main/java/mx/edu/utez/pret/controller/EstadoVacanteController.java
> +        return new ResponseEntity<>(response.buildStandardResponse("Obtener todos los estadosVacante",
Cambiar la el mensaje de la entidad por como se escribiría normalmente (estados de la vacante).

2022-07-18 19:44 UTC, GandyA23 commented on src/main/java/mx/edu/utez/pret/controller/EstadoVacanteController.java
> +            : response.buildStandardResponse(title, null, String.format("El estadoVacante con el id %d no existe", idL));
Cambiar la el mensaje de la entidad por como se escribiría normalmente.

2022-07-18 19:44 UTC, GandyA23 commented on src/main/java/mx/edu/utez/pret/controller/EstadoRepublicaController.java
> +            : response.buildStandardResponse(title, null, String.format("El estadoRepublica con el id %d no existe", idL));
Cambiar la el mensaje de la entidad por como se escribiría normalmente.

2022-07-18 19:44 UTC, GandyA23 commented on src/main/java/mx/edu/utez/pret/controller/EstadoVacanteController.java
> +        String title = "Obtener un estadoVacante";
Cambiar la el mensaje de la entidad por como se escribiría normalmente.

2022-07-18 19:44 UTC, GandyA23 commented on src/main/java/mx/edu/utez/pret/controller/EstadoRepublicaController.java
> +        String title = "Obtener un estadoRepublica";
Cambiar la el mensaje de la entidad por como se escribiría normalmente.

2022-07-19 14:18 UTC, GustavoLopez04 commented
Cambio de sintaxis en EstadoVacanteController y EstadoRepublicaController

2022-07-19 19:29 UTC, GandyA23 approved these changes

2022-07-19 19:29 UTC, merged